[tool.poetry]
name = "python-graphql-sample"
version = "0.1.0"
description = ""
authors = ["nasum <nasu@scouty.co.jp>"]

[tool.poetry.dependencies]
python = "^3.6"
graphene = "^2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
